name: Build and deploy Nextra project to the server
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@main
      - name: build static files
        run: npm install && npm run build
      - name: deploy to the server
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: ./out/
          remote_path: /www/wwwroot/learn2web.topfyf.cn/
          remote_host: 1.15.36.71
          remote_user: www-server
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
