name: build and deploy Nextra project to the server
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@main
      - name: build static files
        run: npm install && npm run build
      - name: deploy to the server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          REMOTE_HOST: '1.15.36.71'
          REMOTE_USER: 'www-server''
          SOURCE: "./out/"
          TARGET: "/www/wwwroot/learn2code_topfyf_cn"
