name: Build and deploy Nextra project to the server
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@main
      - name: build static files
        run: npm install && npm run build
      - name: deploy to the server
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASS }}
          localDir: ./out/
          remoteDir: .
          options: "--delete --asci"
